import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anton Porfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar></Navbar>
    </div>
  )
}
